// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1GT6uy4OA8wsOlts1PrDEuwZ2vp1jhLo',
    appId: '1:267018821989:web:4582043c6956e8a0a5018c',
    messagingSenderId: '267018821989',
    projectId: 'hackanime',
    authDomain: 'hackanime.firebaseapp.com',
    storageBucket: 'hackanime.appspot.com',
    measurementId: 'G-XFYTFVHDSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjt_ZR1W5yFsLxApJXp7LRWbVLZVnO9ng',
    appId: '1:267018821989:android:fdbaaa49682ccb0ca5018c',
    messagingSenderId: '267018821989',
    projectId: 'hackanime',
    storageBucket: 'hackanime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9YQaGU-Ho6XVeFsbyzlvOdamyZ-vPVA',
    appId: '1:267018821989:ios:339e6257f3cf6c05a5018c',
    messagingSenderId: '267018821989',
    projectId: 'hackanime',
    storageBucket: 'hackanime.appspot.com',
    iosClientId: '267018821989-hasfd7277toqpj8hmhd22smpo98qut1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackanime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC9YQaGU-Ho6XVeFsbyzlvOdamyZ-vPVA',
    appId: '1:267018821989:ios:339e6257f3cf6c05a5018c',
    messagingSenderId: '267018821989',
    projectId: 'hackanime',
    storageBucket: 'hackanime.appspot.com',
    iosClientId: '267018821989-hasfd7277toqpj8hmhd22smpo98qut1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackanime',
  );
}

